format = """\
${custom.arch}\
$directory\
$git_branch\
$git_status\
$fill\
\n$character\
"""

[directory]
truncate_to_repo = false

[git_branch]
style = "#008000"

[git_status]
conflicted = '💥'
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = '✓'
untracked = '?'
stashed = '📦'
modified = '!${count}'
renamed = '»'
deleted = '✘'

[custom.arch]
command = "echo $GET_TERMINAL_ARCHITECTURE"
when = "true"
format = "[\\[($output)\\]](purple) "

[fill]
symbol = '.'
